import * as THREE from "three";
import React, { useRef } from "react";
import { useLoader, useFrame } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: Guad (https://sketchfab.com/GuadalupeD)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/palm-tree-c520a0429a024f18a69342ce79acd5d5
title: Palm Tree
*/

const PalmTree = ({ ...props }) => {
	const { nodes } = useLoader(GLTFLoader, "../scene.gltf");

	const material = new THREE.MeshStandardMaterial({
		color: new THREE.Color("#6D292B"),
		roughness: 1,
		metalness: 0,
	});

	const leaves = useRef();
	const leaves2 = useRef();

	useFrame(({ clock }) => {
		leaves.current.rotation.y = leaves2.current.rotation.x =
			Math.sin(clock.getElapsedTime()) * -0.015;
		leaves2.current.rotation.z = Math.sin(clock.getElapsedTime()) * 0.015;
	});

	return (
		<group {...props}>
			<mesh
				ref={leaves}
				material={material}
				geometry={nodes.mesh_0.geometry}
			/>
			<mesh
				ref={leaves2}
				material={material}
				geometry={nodes.mesh_1.geometry}
			/>
			<mesh material={material} geometry={nodes.mesh_2.geometry} />
		</group>
	);
};

export default PalmTree;
